
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "@/(components)/layouts/Header";
import Footer from "@/(components)/layouts/Footer";
import Providers from "@/(components)/ThemeProvider";
import ScrollToTopBtn from "@/(components)/layouts/ScrollToTopBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});



export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col  bg-white text-black dark:bg-black dark:text-white ${playfair.className}`}>
        <Providers>
      <Header />
      {children}
      <ScrollToTopBtn />
      <Footer />
    </Providers>
      </body>
    </html>
  );
}
